deployments:
  nodocker:
    dockerimage: nginx
    squash-cmd--aws-credentials:
      aws_access_key: $ACCESS_KEY
      aws_secret_key: $SECRET_KEY
      region: us-east-2
    pipelines:
      - default:
          scripts:
            - echo true
      - secondary:
          scripts:
            - sleep 30 && ls -la
