deployments:
  nginx:
    dockerimage: nginx
    pipelines:
      - default:
          scripts:
            - echo true
      - secondary:
          scripts:
            - sleep 30 && ls -la
  apache:
    dockerimage: httpd
    pipelines:
      - default:
          scripts:
            - echo 'something v2'
