deployments:
  nodocker:
    dockerimage: nginx
    squash-cmd--aws-credentials:
      aws_access_key: $ACCESS_KEY
      aws_secret_key: $SECRET_KEY
      region: us-east-2
    pipelines:
      - default:
          dockerimage: phusion/baseimage:0.9.18
          build_steps:
            - echo something
            - apt-get install -y wget
            - ls -la
            - echo finished
          scripts:
            - echo true
